name: build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: alexellis/arkade-get@setup
      with:
        faas-cli: latest
    - run: |
        faas-cli version
