name: build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: alexellis/setup-arkade@v1
    - name: check PATH
      run: echo $PATH
