name: build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: alexellis/arkade-get@master
      with:
#        print-summaries: false
        faas-cli: latest
        k3sup: latest
        kubectl: latest
        k9s: latest
        k3s: latest
    - run: |
        faas-cli version
        k3sup version
